version: 2
updates:
    # Update npm dependencies
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 10
      labels:
          - 'dependencies'
          - 'auto-merge'
      # Enable automerge for npm dependencies
      auto-merge: true
      commit-message:
          prefix: "build"

    # Update GitHub Actions workflows
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'dependencies'
          - 'auto-merge'
      # Enable automerge for GitHub Actions dependencies
      auto-merge: true
      commit-message:
          prefix: "chore"